### PR TITLE
Use content instead of label attribute for compatibility with 1.0 pap…

### PR DESCRIPTION
**Pull request by rubenstolk**
…er-radio-button

### CODE REVIEW

**Comment by notwaldorf** [comment]
Ah, good catch. Thanks for the contribution!

**Comment by notwaldorf** [comment]
@rubenstolk I accidentally merged this before checking that you signed the CLA. Could you do that, please? Sorry!

**Comment by rubenstolk** [comment]
I signed it!

**Comment by notwaldorf** [comment]
Thanks!

**Comment by lee101** [comment]
@notwaldorf for some reason i can't see this commit on master

**Comment by notwaldorf** [comment]
@lee101 Yeaaaaah I can't either. Something's gone weird with this PR. I'll open a new PR.

**Pull request merged**
